name: 'dbt_meetup_2025_march'

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:      
  - "target"
  - "dbt_packages"


models:
  dbt_meetup_2025_march:
    +materialized: view

tests:
  dbt_meetup_2025_march:
    +tags: ["unit-test"]


vars:
  dbt_source_tags: ["yandex-ads"]
  unit_tests_config:
      input_format: "csv"
      column_separator: "|"
      line_separator: "\n"
      type_separator: "::"
      last_spaces_replace_char: "."